# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 03:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alarm_name', models.CharField(max_length=48, verbose_name='\u62a5\u8b66\u540d\u79f0')),
                ('Alarm_url', models.CharField(max_length=48, verbose_name='\u89e6\u53d1\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u62a5\u8b66\u65b9\u5f0f',
                'verbose_name_plural': '\u62a5\u8b66\u65b9\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='IDCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDC_name', models.CharField(max_length=48, verbose_name='idc\u673a\u623f')),
                ('IDC_url', models.URLField(max_length=128, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'IDC\u673a\u623f\u4fe1\u606f',
                'verbose_name_plural': 'IDC\u673a\u623f\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Req_Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_req_count', models.IntegerField(verbose_name='\u6b63\u5e38\u8bf7\u6c42\u6b21\u6570')),
                ('alarm_req_count', models.IntegerField(verbose_name='\u62a5\u8b66\u8bf7\u6c42\u6b21\u6570')),
                ('unreachable_req_count', models.IntegerField(verbose_name='\u4e0d\u53ef\u8fbe\u6b21\u6570')),
                ('server_id', models.CharField(max_length=128, verbose_name='\u670d\u52a1ID')),
                ('server_name', models.CharField(max_length=128, verbose_name='\u670d\u52a1\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u8bf7\u6c42\u6b21\u6570\u7edf\u8ba1',
                'verbose_name_plural': '\u8bf7\u6c42\u6b21\u6570\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='ReqInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=128, verbose_name='\u670d\u52a1ID')),
                ('server_name', models.CharField(max_length=128, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('alarm_user', models.CharField(max_length=1024, verbose_name='\u62a5\u8b66\u5bf9\u8c61')),
                ('server_status', models.CharField(max_length=512, verbose_name='\u670d\u52a1\u72b6\u6001')),
                ('is_alarm', models.BooleanField(verbose_name='\u662f\u5426\u62a5\u8b66')),
                ('interval', models.IntegerField(verbose_name='\u62a5\u8b66\u95f4\u9694')),
                ('req_date', models.DateTimeField(verbose_name='\u8bf7\u6c42\u65f6\u95f4')),
                ('other', models.CharField(max_length=128, verbose_name='\u5176\u4ed6')),
                ('is_unreachable', models.BooleanField(default=False, verbose_name='\u4e0d\u53ef\u8fbe\u8bf7\u6c42')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_API.AlarmInfo', verbose_name='\u62a5\u8b66\u65b9\u5f0f')),
            ],
            options={
                'verbose_name': '\u8bf7\u6c42\u6570\u636e',
                'verbose_name_plural': '\u8bf7\u6c42\u6570\u636e',
            },
        ),
        migrations.CreateModel(
            name='Server_Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=128, verbose_name='\u670d\u52a1ID')),
                ('server_name', models.CharField(max_length=128, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('inspection_interval', models.IntegerField(verbose_name='\u68c0\u6d4b\u95f4\u9694')),
                ('alarm_user', models.CharField(max_length=1024, verbose_name='\u62a5\u8b66\u5bf9\u8c61')),
                ('last_alarm_date', models.DateTimeField(default=datetime.datetime(2017, 1, 6, 11, 7, 28, 960000), verbose_name='\u4e0a\u6b21\u672a\u68c0\u6d4b\u5230\u7684\u62a5\u8b66\u65f6\u95f4')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_API.AlarmInfo', verbose_name='\u62a5\u8b66\u65b9\u5f0f')),
            ],
            options={
                'verbose_name': '\u76d1\u63a7\u670d\u52a1\u6ce8\u518c',
                'verbose_name_plural': '\u76d1\u63a7\u670d\u52a1\u6ce8\u518c',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('project', models.CharField(choices=[(b'DK', '\u5927\u5361'), (b'HY', '\u8d27\u8fd0'), (b'YY', '\u8fd0\u8425'), (b'YYZC', '\u8fd0\u8425\u652f\u6491'), (b'ZY', '\u667a\u8fd0')], max_length=48, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('IDC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_API.IDCInfo')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='server_reg',
            name='req_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_API.UserInfo', verbose_name='\u8bf7\u6c42\u8005'),
        ),
        migrations.AddField(
            model_name='reqinfo',
            name='req_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_API.UserInfo', verbose_name='\u8bf7\u6c42\u8005'),
        ),
        migrations.AddField(
            model_name='req_statistics',
            name='req_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_API.UserInfo', verbose_name='\u8bf7\u6c42\u8005'),
        ),
    ]
